### ISSUE TITLE
Using commit that updates checksums does not allow new versions

### ISSUE THREAD

**Issue by lock14** [abcxyz/secure-setup-terraform#106]
### TL;DR

If I use the following github action configuration
```
      - name: 'Setup Terraform'
        uses: 'abcxyz/secure-setup-terraform@4d361110d3718e05b118be20051ba2855a2cc9e1'
        with:
          terraform_version: '1.7.1`
          protect_lockfile: true
          terraform_wrapper: false
```
the action will fail with the message
```
shasum: terraform.sha256: no properly formatted SHA checksum lines found
```
even though there is a checksum for version 1.7.1 in for commit `4d361110d3718e05b118be20051ba2855a2cc9e1`
https://github.com/abcxyz/secure-setup-terraform/commit/4d361110d3718e05b118be20051ba2855a2cc9e1

### Environment Details

```markdown
Standard GitHub action environment
```
